Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 31, in search_child_api
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 146, in verify
    img1_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 105, in extract_faces
    img_region = [0, 0, img.shape[1], img.shape[0]]
AttributeError: 'NoneType' object has no attribute 'shape'
Internal Server Error: /api/search_child_api/
Creating converter from 3 to 5
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picSearch\settings.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Not Found: /favicon.ico
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\demo.jpg exists
tag: ImageWidth (256) - type: long (4) - value: b'\x00\x00\n '
tag: ImageLength (257) - type: long (4) - value: b'\x00\x00\x07\x98'
tag: Copyright (33432) - type: string (2) Tag Location: 46 - Data Location: 206 - value: b'Copyright,Spreadtrum,2011\x00'
tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
tag: ImageDescription (270) - type: string (2) Tag Location: 70 - Data Location: 232 - value: b'Exif_JPEG_420\x00'
tag: Make (271) - type: string (2) Tag Location: 82 - Data Location: 246 - value: b'ITEL MOBILE LIMITED\x00'
tag: Model (272) - type: string (2) Tag Location: 94 - Data Location: 266 - value: b'itel L6006S\x00'
tag: Software (305) - type: string (2) Tag Location: 106 - Data Location: 278 - value: b'Software Version v1.1.0\x00'
tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
tag: DateTime (306) - type: string (2) Tag Location: 130 - Data Location: 302 - value: b'2021:09:19 13:36:35\x00'
tag: YCbCrPositioning (531) - type: short (3) - value: b'\x00\x01'
tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x01_'
tag: GPSInfoIFD (34853) - type: long (4) - value: b'\x00\x00\x038'
tag: XResolution (282) - type: rational (5) Tag Location: 178 - Data Location: 322 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
tag: YResolution (283) - type: rational (5) Tag Location: 190 - Data Location: 330 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
tag: Artist (315) - type: string (2) Tag Location: 202 - Data Location: 338 - value: b'Artist-freed\x00'
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 84, in search_child
    return render(request, 'search_results.html', {'similar_children': similar_children})
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1/1 + distance) * 100' from '(1/1 + distance) * 100'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    similarity = 1 / (1 + 'distance') * 100
TypeError: unsupported operand type(s) for +: 'int' and 'str'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    distance = float('distance')
ValueError: could not convert string to float: 'distance'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    distance = float(distance)
UnboundLocalError: local variable 'distance' referenced before assignment
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /
Creating converter from 3 to 5
Not Found: /favicon.ico
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Not Found: /favicon.ico
Creating converter from 3 to 5
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Starting new HTTPS connection (1): github.com:443
https://github.com:443 "GET /serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5 HTTP/1.1" 302 0
Starting new HTTPS connection (1): objects.githubusercontent.com:443
https://objects.githubusercontent.com:443 "GET /github-production-release-asset-2e65be/382368840/6bf9ba80-db5a-11eb-8b48-84b0d02a64ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230524T121151Z&X-Amz-Expires=300&X-Amz-Signature=572edcc11dc5bdc896cfe4da9ab00a231240768a7d0747aadf61d73baf0a59b6&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=382368840&response-content-disposition=attachment%3B%20filename%3Dvgg_face_weights.h5&response-content-type=application%2Foctet-stream HTTP/1.1" 200 580085408
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Starting new HTTPS connection (1): github.com:443
https://github.com:443 "GET /serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5 HTTP/1.1" 302 0
Starting new HTTPS connection (1): objects.githubusercontent.com:443
https://objects.githubusercontent.com:443 "GET /github-production-release-asset-2e65be/382368840/0c6bd100-db93-11eb-819c-0b61869108d3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230524T122656Z&X-Amz-Expires=300&X-Amz-Signature=29170963f87718efc48d72f0b69baf0c503aadda2934748aa7ef7b10c2605cc4&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=382368840&response-content-disposition=attachment%3B%20filename%3Dfacial_expression_model_weights.h5&response-content-type=application%2Foctet-stream HTTP/1.1" 200 5977392
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
/home/silver/Hackathon/ImageSearch/picSearch/picApp/forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /
Not Found: /favicon.ico
/home/silver/Hackathon/ImageSearch/picSearch/picApp/forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
/home/silver/Hackathon/ImageSearch/picSearch/picApp/forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Creating converter from 3 to 5
Internal Server Error: /submit/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'age' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 47, in submit_child
    child.save()
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'age' cannot be null")
/home/silver/Hackathon/ImageSearch/picSearch/picApp/models.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 68, in search_child
    temp_image.close()
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 820, in detectFace
    face_objs = extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 64, in search_child
    detected_faces = DeepFace.extract_faces(temp_image.name, enforce_detection=True)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 64, in search_child
    detected_faces = DeepFace.extract_faces(temp_image.name, enforce_detection=True)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 64, in search_child
    detected_faces = DeepFace.extract_faces(temp_image.name, enforce_detection=True)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 64, in search_child
    detected_faces = DeepFace.extract_faces(temp_image.name, enforce_detection=True)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py", line 64, in search_child
    detected_faces = DeepFace.extract_faces(temp_image.name, enforce_detection=True)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 787, in extract_faces
    img_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 115, in extract_faces
    raise ValueError(
ValueError: Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Bad Request: /api/search_child_api/
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
Creating converter from 3 to 5
Bad Request: /api/search_child_api/
