Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 31, in search_child_api
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/DeepFace.py", line 146, in verify
    img1_objs = functions.extract_faces(
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/deepface/commons/functions.py", line 105, in extract_faces
    img_region = [0, 0, img.shape[1], img.shape[0]]
AttributeError: 'NoneType' object has no attribute 'shape'
Internal Server Error: /api/search_child_api/
Creating converter from 3 to 5
An error occurred when searching for the child
Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py", line 19, in search_child_api
    image = request.FILES['image']
  File "/home/silver/Hackathon/ImageSearch/myenv/lib/python3.9/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'image'
Internal Server Error: /api/search_child_api/
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picSearch\settings.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Not Found: /favicon.ico
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\IMG_20210919_133635.jpg exists
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 73, in search_child
    similarity = DeepFace.verify(temp_image.name, child_image_path, model_name='Facenet', distance_metric='euclidean_l2', enforce_detection=False)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\DeepFace.py", line 155, in verify
    img2_objs = functions.extract_faces(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 104, in extract_faces
    img = load_image(img)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\deepface\commons\functions.py", line 81, in load_image
    raise ValueError(f"Confirm that {img} exists")
ValueError: Confirm that C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\media\missing_children\demo.jpg exists
tag: ImageWidth (256) - type: long (4) - value: b'\x00\x00\n '
tag: ImageLength (257) - type: long (4) - value: b'\x00\x00\x07\x98'
tag: Copyright (33432) - type: string (2) Tag Location: 46 - Data Location: 206 - value: b'Copyright,Spreadtrum,2011\x00'
tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
tag: ImageDescription (270) - type: string (2) Tag Location: 70 - Data Location: 232 - value: b'Exif_JPEG_420\x00'
tag: Make (271) - type: string (2) Tag Location: 82 - Data Location: 246 - value: b'ITEL MOBILE LIMITED\x00'
tag: Model (272) - type: string (2) Tag Location: 94 - Data Location: 266 - value: b'itel L6006S\x00'
tag: Software (305) - type: string (2) Tag Location: 106 - Data Location: 278 - value: b'Software Version v1.1.0\x00'
tag: Orientation (274) - type: short (3) - value: b'\x00\x00'
tag: DateTime (306) - type: string (2) Tag Location: 130 - Data Location: 302 - value: b'2021:09:19 13:36:35\x00'
tag: YCbCrPositioning (531) - type: short (3) - value: b'\x00\x01'
tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x01_'
tag: GPSInfoIFD (34853) - type: long (4) - value: b'\x00\x00\x038'
tag: XResolution (282) - type: rational (5) Tag Location: 178 - Data Location: 322 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
tag: YResolution (283) - type: rational (5) Tag Location: 190 - Data Location: 330 - value: b'\x00\x00\x00H\x00\x00\x00\x01'
tag: Artist (315) - type: string (2) Tag Location: 202 - Data Location: 338 - value: b'Artist-freed\x00'
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 84, in search_child
    return render(request, 'search_results.html', {'similar_children': similar_children})
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1/1 + distance) * 100' from '(1/1 + distance) * 100'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    similarity = 1 / (1 + 'distance') * 100
TypeError: unsupported operand type(s) for +: 'int' and 'str'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    distance = float('distance')
ValueError: could not convert string to float: 'distance'
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py", line 76, in search_child
    distance = float(distance)
UnboundLocalError: local variable 'distance' referenced before assignment
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /
Creating converter from 3 to 5
Not Found: /favicon.ico
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Not Found: /favicon.ico
Not Found: /favicon.ico
Creating converter from 3 to 5
Not Found: /favicon.ico
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
C:\Users\hp\Documents\H-IT\ImageSearch\ImageSearch\ImageSearch\picSearch\picApp\forms.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
/home/silver/Hackathon/ImageSearch/picSearch/picApp/api.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 3 to 5
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
/home/silver/Hackathon/ImageSearch/picSearch/picApp/views.py changed, reloading.
Watching for file changes with StatReloader
Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
Creating converter from 7 to 5
Creating converter from 5 to 7
Creating converter from 7 to 5
Creating converter from 5 to 7
Watching for file changes with StatReloader
